version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_REPORTING_DISABLED=false
    networks:
      - backend
    volumes:
      - ${PWD}/influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "8080:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - backend
    volumes:
      - ${PWD}/grafana-data:/var/lib/grafana

networks:
  backend:
