version: "2"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086"
    env_file:
      - 'env.influxdb'
    networks:
      - backend
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb

#  telegraf:
#    image: telegraf:latest
#    container_name: telegraf
#    networks:
#      - backend
#    volumes:
#      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
      - 'secret.grafana'
    networks:
      - backend
    volumes:
      - /var/lib/grafana:/var/lib/grafana

networks:
  backend:
